In [22]:
import pandas as pd
import os

In [23]:
input_file = "D:\\Magang\\Projek\\Review Prosedur\\dokumen\\data-review-prosedur.xlsx"
output_folder = "../dokumen"

os.makedirs(output_folder, exist_ok=True)

In [24]:
df = pd.read_excel(input_file)

# Pastikan kolom PIC ada
if "PIC" not in df.columns:
    raise ValueError("Kolom 'PIC' tidak ditemukan di file Excel")

grouped = df.groupby("PIC")

for pic_name, data_pic in grouped:
    # Bersihkan nama PIC agar aman untuk nama file
    safe_pic_name = str(pic_name).replace("/", "_").replace("\\", "_")
    
    output_file = os.path.join(
        output_folder,
        f"dokumen_{safe_pic_name}.xlsx"
    )
    
    # Simpan ke Excel
    data_pic.to_excel(output_file, index=False)
    
    print(f"File dibuat: {output_file}")

print("Proses selesai 🎉")

File dibuat: ../dokumen\dokumen_ACA.xlsx
File dibuat: ../dokumen\dokumen_AIN.xlsx
File dibuat: ../dokumen\dokumen_ASE.xlsx
File dibuat: ../dokumen\dokumen_ASW.xlsx
File dibuat: ../dokumen\dokumen_ATH.xlsx
File dibuat: ../dokumen\dokumen_CHA.xlsx
File dibuat: ../dokumen\dokumen_DAF,YHE,TWI.xlsx
File dibuat: ../dokumen\dokumen_DAS.xlsx
File dibuat: ../dokumen\dokumen_DHS.xlsx
File dibuat: ../dokumen\dokumen_DKR.xlsx
File dibuat: ../dokumen\dokumen_EMU.xlsx
File dibuat: ../dokumen\dokumen_ENS.xlsx
File dibuat: ../dokumen\dokumen_ENS, TWI.xlsx
File dibuat: ../dokumen\dokumen_FIR.xlsx
File dibuat: ../dokumen\dokumen_HMA.xlsx
File dibuat: ../dokumen\dokumen_HPU.xlsx
File dibuat: ../dokumen\dokumen_HPU,TWI,DAS,YFI.xlsx
File dibuat: ../dokumen\dokumen_HSW.xlsx
File dibuat: ../dokumen\dokumen_ISR.xlsx
File dibuat: ../dokumen\dokumen_ISR, AIN.xlsx
File dibuat: ../dokumen\dokumen_LDA.xlsx
File dibuat: ../dokumen\dokumen_LSE.xlsx
File dibuat: ../dokumen\dokumen_MCB.xlsx
File dibuat: ../dokumen\dokumen_MCB, DHS.xlsx
File dibuat: ../dokumen\dokumen_MMR.xlsx
File dibuat: ../dokumen\dokumen_NIA.xlsx
File dibuat: ../dokumen\dokumen_RKO.xlsx
File dibuat: ../dokumen\dokumen_SFE.xlsx
File dibuat: ../dokumen\dokumen_TWI.xlsx
File dibuat: ../dokumen\dokumen_VRA.xlsx
File dibuat: ../dokumen\dokumen_VRA, ASW.xlsx
File dibuat: ../dokumen\dokumen_WSU.xlsx
File dibuat: ../dokumen\dokumen_WWI.xlsx
File dibuat: ../dokumen\dokumen_YFI.xlsx
File dibuat: ../dokumen\dokumen_YHE.xlsx
Proses selesai 🎉

In [25]:
df_ACA = pd.read_excel("../dokumen/dokumen_ACA.xlsx")
df_ACA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
0,Power Failure (Black Out),PFP-W-22,3,2025-06-25,1,PGA,ACA
1,Air Compression Failure,PFP-W-23,3,2025-06-25,1,PGA,ACA
2,Water Supply Interuption,PFP-W-24,3,2022-09-21,0,PGA,ACA
3,Penambahan Daya Listrik,PFP-W-29,3,2025-08-25,0,PGA,ACA

In [3]:
import pandas as pd

data = pd.read_excel("../dokumen/data-review-prosedur.xlsx")
data.head()

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
0,Business Plan,BPR-P-01,2,2025-10-01,8,QSA,ISR
1,Risk Analysis,BPR-W-01,3,2025-07-31,3,QSA,ISR
2,Business Operating System (BOS),BOS-P-01,2,2025-10-01,4,QSA,ISR
3,Customer Satisfaction,BOS-W-02,3,2017-07-03,2,QSA,ISR
4,Work In Process Finish Good,BOS-W-03,3,2025-10-13,1,PRODUKSI,ENS

In [4]:
by_group = data.groupby("PIC")
daftar_pic = {
    'PIC' : []
}

print("="*40)
print("Data Pecah Berdasarkan PIC")
print(f"PIC terbanyak : {by_group.size().idxmax()}")
print(f"Dengan Jumlah Dokumen : {by_group.size().max()}")
print("="*40)

c=1
for pic , name in by_group:
    daftar_pic['PIC'].append(pic)
    print(f"{c}. {pic}")
    display(name)
    c+=1

df_pic = pd.DataFrame(daftar_pic)
display(df_pic)

========================================
Data Pecah Berdasarkan PIC
PIC terbanyak : TWI
Dengan Jumlah Dokumen : 33
========================================
1. ACA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
211,Power Failure (Black Out),PFP-W-22,3,2025-06-25,1,PGA,ACA
212,Air Compression Failure,PFP-W-23,3,2025-06-25,1,PGA,ACA
213,Water Supply Interuption,PFP-W-24,3,2022-09-21,0,PGA,ACA
217,Penambahan Daya Listrik,PFP-W-29,3,2025-08-25,0,PGA,ACA

2. AIN

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
214,Chemical Spills (Tumpahan B3 Cair),PFP-W-25,3,2022-11-24,0,PGA,AIN
216,Fire Minor,PFP-W-28,3,2025-08-05,1,PGA,AIN

3. ASE

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
193,Finished Goods Storage & Delivery,FSD-P-01,2,2025-08-13,10,EXIM,ASE
194,Loading to Container,FSD-W-01,3,2025-08-13,4,EXIM,ASE
195,Penarikan dan Penyusunan F/G di area Loading Dock,FSD-W-02,3,2025-08-12,4,EXIM,ASE

4. ASW

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
17,Moto Audit,IAU-W-13,3,2025-08-13,5,QC STANDARISASI,ASW
57,Pembuatan & Pengontrolan Inspection Standard (IS),PQP-W-11,3,2025-08-13,5,QC STANDARISASI,ASW
74,Control of Part Design Change,CDC-W-11,3,2025-08-08,6,QC REC,ASW
111,Material Receiving And Storage,MRS-P-01,2,2025-05-20,8,"QC REC, WHS",ASW
112,Quality Receiving Inspection,MRS-W-02,3,2025-07-31,8,QC REC,ASW
113,Rec. Insp. For Abnormal Condition,MRS-W-03,3,2025-11-14,2,QC REC,ASW
114,Pembuatan Receiving Inspection Standard,MRS-W-05,3,2025-07-31,2,QC REC,ASW
115,Pengisian CS Pemeriksaan Ulang Part / Material,MRS-W-10,3,2025-11-07,4,QC REC,ASW
116,Material Alert,MRS-W-11,3,2025-11-07,4,QC REC,ASW
120,Control New Part & Similar Part,MRS-W-23,3,2021-06-04,2,QC REC,ASW
189,Control Nonconforming Part / Material,CNP-P-02,2,2024-06-04,9,QC REC,ASW
190,Pembuatan dan Follow Up Defective Report,CNP-W-01,3,2025-08-05,7,QC REC,ASW
191,"Pembuatan Summary Report ""Sorting Cost of Defe...",CNP-W-02,3,2025-08-13,6,QC REC,ASW
192,Pemeriksaan Part Material 100%,CNP-W-03,3,2025-11-14,4,QC REC,ASW

5. ATH

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
26,ID Card Karyawan & Temporary ID,HRM-W-15,3,2011-04-13,1,HR,ATH
27,Pelaksanaan Kerja Lembur,HRM-W-14,3,2022-11-01,4,HR,ATH
39,Pengambilan & Pengembalian Form Catatan Mening...,HRM-W-22,3,2025-08-06,1,HR,ATH
48,Medical Emergency,HRM-W-36,3,2025-08-18,1,"HR, IR",ATH

6. CHA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
56,Pembuatan & Review Berkala Production Process ...,PQP-W-10,3,2025-08-07,6,DSG,CHA
68,Pembuatan Dokumen Engineering Design and Standard,CDC-W-01,3,2025-08-07,5,DSG,CHA
69,Proses Input Part List di AS 400,CDC-W-02,3,2025-08-07,3,DSG,CHA
70,Pembuatan Engineering Package,CDC-W-03,3,2025-08-07,8,DSG,CHA
72,Print Clarification Dan Design Request,CDC-W-07,3,2008-10-28,4,DSG,CHA
79,Control Circuit Dalam Joint Yang Sama,CDC-W-22,3,2025-08-07,1,DSG,CHA

7. DAF,YHE,TWI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
171,Standard Setting Torque Driver & Torque Checker,FAM-W-13,3,2025-11-13,4,"PD, PE, QC MSA","DAF,YHE,TWI"
245,Verifikasi Torque,CMD-W-03,3,2025-08-11,2,"PD, PE, QC MSA","DAF,YHE,TWI"

8. DAS

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
88,Pengontrolan Polytainer Dan Pallet Rental,PPL-W-05,3,2025-08-06,4,MPC,DAS
95,Pengadaan PSW Material,MOR-W-05,3,2025-08-06,5,MPC,DAS
101,Analisa Material,MOR-W-12,3,2025-04-15,5,MPC,DAS
103,Air Freight Request,MOR-W-15,3,2025-08-06,4,MPC,DAS
118,Mekanisme Pengontrolan Dan Pengecekan SOC Untu...,MRS-W-16,3,2024-09-26,8,MPC,DAS
119,Claim Dead Stock Material ke Customer,MRS-W-18,3,2025-08-06,4,MPC,DAS
130,Persiapan SoC Sample Untuk Pengecekan Phthlate...,MRS-W-36,3,2025-12-12,0,MPC,DAS

9. DHS

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
202,Pembuatan Jig Board Drawing,PFP-W-03,3,2014-04-14,1,PE,DHS
203,Pembuatan Cheker Program,PFP-W-05,3,2004-07-01,0,PE,DHS
204,Pembuatan Jig Board,PFP-W-06,3,2004-09-28,0,PE,DHS
206,Approval dan Verifikasi Jig Board,PFP-W-10,3,2007-10-18,5,PE,DHS
207,Checker Progran Validation,PFP-W-13,3,2004-06-29,0,PE,DHS
208,Kebutuhan Special Equipment,PFP-W-14,3,2025-08-20,1,"PE, PD",DHS
220,Penyediaan Dan Pengadaan Part / Equipment,ETM-W-02,3,2025-08-20,2,PE,DHS
227,Production Equipment Breakdown,ETM-W-19,3,2025-08-20,1,PE,DHS
236,Preventive Maintenance Equipment Final Assy,PPM-W-06,3,2025-08-20,7,PE,DHS
237,Pengisian CS Patroli Harian Equipment Final Assy,PPM-W-08,3,2025-05-20,3,PE,DHS

10. DKR

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
231,Stock Opname Sparepart,ETM-W-23,3,2025-06-12,0,MTC SC,DKR

11. EMU

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
67,Design Change,CDC-P-01,2,2025-08-12,16,PPC,EMU
83,Production Plan,PPL-P-01,2,2025-08-14,6,PPC,EMU
84,Pembuatan Sample Build Timing,PPL-W-01,3,2025-08-14,3,PPC,EMU
85,Pembuatan SPP ( Six Months Production Plan ),PPL-W-02,3,2025-08-19,5,PPC,EMU
86,Pembuatan Assy Plan,PPL-W-03,3,2025-08-14,4,PPC,EMU
87,Follow Up Delay Produksi,PPL-W-04,3,2025-08-19,2,PPC,EMU
90,Production Plan for Part & Service,PPL-W-07,3,2025-04-28,3,PPC,EMU
91,Request Air Freight Finish Goods,PPL-W-08,3,2025-08-14,1,PPC,EMU
92,Increase And Decrease Order,PPL-W-11,3,2025-08-14,2,PPC,EMU
94,Input Assy Plan Di AS 400,MOR-W-01,3,2025-08-14,2,PPC,EMU
196,Shipping Release Review,FSD-W-09,3,2025-08-12,3,PPC,EMU
197,Repacking Process,FSD-W-10,3,2025-08-14,1,PPC,EMU
198,Pembuatan Invoice Finish Good,FSD-W-11,3,2025-08-14,3,PPC,EMU

12. ENS

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
4,Work In Process Finish Good,BOS-W-03,3,2025-10-13,1,PRODUKSI,ENS
128,Penyediaan Tube Untuk Produksi,MRS-W-35,3,2025-10-23,3,PRODUKSI,ENS
136,Pengisian CS LK Operator & Inspector Gun / Dip...,PAM-W-06,3,2025-08-15,4,PRODUKSI,ENS
138,Pengisian CS LK Operator Dan Inspektor Man. Cr...,PAM-W-08,3,2022-11-03,14,PRODUKSI,ENS
139,Pengisian CS LK Operator Middle Stripping,PAM-W-09,3,2025-08-15,4,PRODUKSI,ENS
140,Pengisian CS LK Operator Wire Twisting,PAM-W-10,3,2025-08-15,9,PRODUKSI,ENS
141,Pengisian CS LK Operator Pemasangan Tube / Acc...,PAM-W-11,3,2025-08-14,5,PRODUKSI,ENS
142,Pengisian CS LK Operator Joint Taping,PAM-W-12,3,2025-08-15,4,PRODUKSI,ENS
143,Pengisian CS LK Operator Manual Taping,PAM-W-13,3,2022-11-03,5,PRODUKSI,ENS
147,Pengisian CS LK Operator Accessories Insertion...,PAM-W-17,3,2019-10-11,0,PRODUKSI,ENS
148,Pengisian CS LK Operator Cutting Doren Shield ...,PAM-W-18,3,2019-10-11,0,PRODUKSI,ENS
151,Pengisian LKO Pemasangan Tube / Accesories Airbag,PAM-W-35,3,2025-08-15,4,PRODUKSI,ENS
152,Quality Tube,PAM-W-37,3,2025-08-13,4,PRODUKSI,ENS
153,Pengisian LKO Rolling Machine Wire /Tube,PAM-W-38,3,2025-08-13,3,PRODUKSI,ENS
155,Pengisian CS Daily Report Prosess Cutting,PAM-W-41,3,2025-08-15,6,PRODUKSI,ENS
156,Pengisian C/S LKO Operator End Stripping,PAM-W-42,3,2025-10-23,4,PRODUKSI,ENS
159,Pengisian C/S Lembar Kerja Operator Proses Ant...,PAM-W-46,3,2023-12-01,0,PRODUKSI,ENS
161,Pengisian C/S Laporan Kerja Operator Hodoki,PAM-W-48,3,2023-12-01,0,PRODUKSI,ENS
162,Pengisian Checksheet Pengecheckan Kekentalan A...,PAM-W-49,3,2024-12-11,1,PRODUKSI,ENS
163,Pengisian Checksheet LKO Cutting Jam Twist,PAM-W-51,3,2025-11-19,0,PRODUKSI,ENS
166,Kontrol Harian Produksi,FAM-W-06,3,2025-08-19,3,PRODUKSI,ENS
168,Pengisian CS Laporan Kerja Operator F/A,FAM-W-08,3,2017-12-14,2,PRODUKSI,ENS
169,Pengisian CS Pengisian Material Mesin Water Pr...,FAM-W-09,3,2020-10-19,3,PRODUKSI,ENS
170,Pengisian C/S Sample Test Mesin Water Proof In...,FAM-W-12,3,2025-08-13,2,PRODUKSI,ENS
172,Pengisian CS Laporan Kerja Operator FA Airbag,FAM-W-16,3,2025-08-13,3,PRODUKSI,ENS
173,Pengisian CS Housing Airbag,FAM-W-17,3,2011-10-18,3,PRODUKSI,ENS
174,Pengisian My QA,FAM-W-19,3,2025-10-13,2,PRODUKSI,ENS
175,Pengisian Defect Tracking Checksheet Removal T...,FAM-W-21,3,2025-08-15,5,PRODUKSI,ENS
177,Proses Torque,FAM-W-27,3,2025-11-14,3,PRODUKSI,ENS
178,Kontrol Pemakaian Name Plate,FAM-W-28,3,2025-10-13,4,PRODUKSI,ENS
205,Form Permintaan Pekerjaan,PFP-W-08,3,2025-10-13,5,PRODUKSI,ENS

13. ENS, TWI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
131,Pre Assembly Process & Inspection,PAM-P-01,2,2025-08-01,3,"PRODUKSI, QA","ENS, TWI"
133,Pengisihan CS LK Operator & Inspector Heat Shr...,PAM-W-02,3,2023-12-02,3,"PRODUKSI, QA","ENS, TWI"
137,Pengisian CS LK Operator Dan Inspektor Cutting,PAM-W-07,3,2025-11-10,16,"PROD, QA, NYS","ENS, TWI"
144,Pengisian CS LK Operator & Inspektor Joint Cri...,PAM-W-14,3,2025-08-15,8,"PRODUKSI, QA","ENS, TWI"
145,Pengisian CS L/K Operator & Inspektor Joint We...,PAM-W-15,3,2025-08-22,10,"PRODUKSI, QA","ENS, TWI"
146,Pengisian CS LK Operator & Inspector Manual Cr...,PAM-W-16,3,2019-10-22,0,"PRODUKSI, QA","ENS, TWI"
154,Rule 4M Transition Pre Assy,PAM-W-39,3,2019-08-08,2,"PRODUKSI, QA","ENS, TWI"
158,Pengisian C/S Lembar Kerja Operator & Inspecto...,PAM-W-45,3,2025-10-13,1,"PRODUKSI, QA","ENS, TWI"
164,Final Assembly Process & Inspection,FAM-P-01,2,2025-08-01,3,"PRODUKSI, QA","ENS, TWI"
165,Proses Inspeksi di Final Assy,FAM-P-02,2,2026-01-15,3,"PRODUKSI, QA","ENS, TWI"
176,Rule 4M Transition Final Assy,FAM-W-23,3,2025-08-06,10,"PRODUKSI, QA","ENS, TWI"
181,Cara Pengisian Form Defective Tag,CNP-W-05,3,2025-08-07,7,"PRODUKSI, QA","ENS, TWI"
186,Pengisian Form Countermeasure Defect,CNP-W-12,3,2025-08-01,2,"PRODUKSI, QA","ENS, TWI"

14. FIR

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
117,Kontrol Material Slow Moving,MRS-W-13,3,2025-08-15,5,WHS,FIR
122,Part Requisition,MRS-W-28,3,2020-04-24,3,WHS,FIR
125,Pembuatan dan Penyimpanan Name Plate,MRS-W-33,3,2024-11-12,8,WHS,FIR
126,Material Supply,MRS-P-02,2,2025-07-29,5,WHS,FIR
129,Stock Opname,MRS-W-34,3,2025-08-11,3,WHS,FIR

15. HMA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
50,Standard Backup Data Komputer,HRM-W-09,3,2018-10-26,2,IT,HMA

16. HPU

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
215,Telecomunication Failure (Telephone),PFP-W-26,3,2022-11-24,0,PGA,HPU
218,Pembuatan Contigency Plan,PFP-P-02,2,2012-10-24,2,PGA,HPU

17. HPU,TWI,DAS,YFI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
110,Pembuatan Application For Advance Payment (AFAP),MOR-W-27,3,2025-09-04,1,"PGA,QA,MPC,FA","HPU,TWI,DAS,YFI"

18. HSW

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
201,Pembuatan Production Layout,PFP-W-02,3,2025-08-06,6,NYS,HSW

19. ISR

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
0,Business Plan,BPR-P-01,2,2025-10-01,8,QSA,ISR
1,Risk Analysis,BPR-W-01,3,2025-07-31,3,QSA,ISR
2,Business Operating System (BOS),BOS-P-01,2,2025-10-01,4,QSA,ISR
3,Customer Satisfaction,BOS-W-02,3,2017-07-03,2,QSA,ISR
5,Management Review,MRE-P-01,2,2025-08-22,6,QSA,ISR
7,Internal Audit,IAU-P-01,2,2025-09-03,14,QSA,ISR
8,Quality Management System Audit,IAU-W-01,3,2025-07-31,3,QSA,ISR
9,Pengisian Form Corrective Action Request (CAR),IAU-W-02,3,2025-07-31,9,QSA,ISR
12,Pemeliharaan & Pengembangan Kompetensi Auditor,IAU-W-07,3,2025-07-31,1,QSA,ISR
14,Second Party Audit,IAU-W-09,3,2025-07-31,3,QSA,ISR
19,Pembuatan Dan Pengendalian Informasi Terdokume...,COD-P-01,2,2025-09-23,11,QSA,ISR
21,Pengendalian Quality Record,COD-W-04,3,2025-08-22,8,QSA,ISR
22,Responsibility and Authority,HRM-P-01,2,2025-08-22,2,TOP MGMT (DEVELOPMENT),ISR

20. ISR, AIN

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
15,Sertifikasi Eksternal,IAU-W-10,3,2025-08-22,1,"QSA, PGA","ISR, AIN"

21. LDA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
51,Product Realization,PQP-P-01,2,2023-09-04,19,PP,LDA
52,Pembuatan PQTP (Product Quality Timing Plan),PQP-W-01,3,2024-05-27,7,PP,LDA
53,Form Pick up Problem,PQP-W-05,3,2010-11-12,2,PP,LDA
54,Risk Assessment,PQP-W-06,3,2007-10-09,2,PP,LDA
60,Offline Training & HVPT,PQP-W-14,3,2007-10-30,0,PP,LDA
62,Production Preparation Cost Control,PQP-W-17,3,2024-06-10,2,PP,LDA
63,Cross Functional Review,PQP-W-18,3,2019-07-31,0,PP,LDA
66,Hinkaku Production Approval,PQP-W-21,3,2024-07-19,0,PP,LDA
78,Pembuatan Dan Perubahan Job Station,CDC-W-15,3,2023-07-21,3,PP,LDA
124,Pengembalian Sisa Material Prototype,MRS-W-31,3,2022-12-12,0,PP,LDA

22. LSE

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
42,Pelaksanaan Kaizen (Improvisasi),HRM-W-28,3,2025-11-10,10,NYS,LSE
43,Aktivitas QC Circle,HRM-W-29,3,2019-10-22,6,NYS,LSE
44,Konvensi QC Circle Internal,HRM-W-30,3,2025-08-12,2,NYS,LSE
89,Pembuatan Instruction Kanban,PPL-W-06,3,2025-11-10,4,NYS,LSE
121,Pembuatan Cutting Kanban Dan Shikake Kanban,MRS-W-25,3,2025-11-10,5,NYS,LSE
127,Pembuatan Kanban Wire Dan Terminal,MRS-W-26,3,2025-11-10,3,NYS,LSE

23. MCB

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
200,Perhitungan Dan Order Kebutuhan Mesin Produksi,PFP-W-01,3,2023-10-19,3,MTC,MCB
221,Set up Tooling Applikator,ETM-W-04,3,2025-07-22,4,MTC,MCB
222,Modifikasi Applicator,ETM-W-05,3,2025-07-22,5,MTC,MCB
223,Penyediaan dan Pengelolaan Spare Part,ETM-W-07,3,2025-07-10,9,MTC,MCB
224,Mapping Applikator,ETM-W-10,3,2025-10-27,4,MTC,MCB
225,Tooling Control Maintenance,ETM-W-13,3,2025-11-10,7,MTC,MCB
226,Sistem Informasi Perubahan Posisi Applicator,ETM-W-15,3,2025-07-24,3,MTC,MCB
233,Preventive and Predictive Maintenance Mesin Pr...,PPM-W-01,3,2024-08-01,7,MTC,MCB
234,Penanganan Kerusakan Pada Mesin Produksi,PPM-W-03,3,2025-08-13,3,MTC,MCB
235,Pelaksanaan Evaluasi Preventive Maintenance M...,PPM-W-05,3,2025-07-22,5,MTC,MCB
238,Pengisian Checksheet Patroli Harian Mesin,PPM-W-10,3,2025-10-27,1,MTC,MCB
239,Review Dokumen (Checksheet) Mesin & Equipment ...,PPM-W-11,3,2025-08-13,1,MTC,MCB

24. MCB, DHS

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
199,Plant and Facility Planning,PFP-P-01,2,2020-07-21,4,"MTC, PROD ENG","MCB, DHS"
219,"Equipment, Tooling & Spare Part Management",ETM-P-01,2,2020-06-24,11,"MTC, PROD ENG","MCB, DHS"
232,Preventive and Predictive Maintenance,PPM-P-01,2,2020-06-24,3,"MTC, PROD ENG","MCB, DHS"

25. MMR

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
93,Material Ordering,MOR-P-01,2,2024-08-19,8,MPC,MMR
96,Line Condition Report,MOR-W-06,3,2025-08-01,3,MPC,MMR
97,Follow Up Over Quantity Shipment,MOR-W-08,3,2025-08-12,4,MPC,MMR
98,Hot Part,MOR-W-09,3,2025-10-24,3,MPC,MMR
99,Follow Up Shipment Delay Part,MOR-W-10,3,2025-08-12,2,MPC,MMR
100,Follow Up Material Order,MOR-W-11,3,2024-10-08,4,MPC,MMR
102,Order Adjustment,MOR-W-14,3,2025-08-12,4,MPC,MMR
105,Flow Informasi Penggunaan Material Jika Terjad...,MOR-W-21,3,2025-11-13,1,MPC,MMR
107,Interruption From Externally Provided,MOR-W-26,3,2025-08-01,1,MPC,MMR
123,New Part,MRS-W-29,3,2024-10-22,2,MPC,MMR

26. NIA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
23,Evaluasi Kinerja Karyawan,HRM-W-02,3,2025-08-15,8,IR,NIA
24,Pelaksanaan Rekruitmen Dengan Syarat Khusus,HRM-W-13,3,2025-12-31,5,IR,NIA
25,Pengunduran Diri,HRM-W-06,3,2025-08-20,7,IR,NIA
45,Mutasi Karyawan,HRM-W-32,3,2025-08-19,1,IR,NIA
49,Tidak Masuk Mogok Kerja & Kekurangan Tenaga Kerja,HRM-W-37,3,2022-06-06,0,IR,NIA

27. RKO

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
106,Standard Agreement Purchase Untuk Non Material...,MOR-W-25,3,2025-11-07,9,PURCHASE,RKO
108,Purchasing,MOR-P-02,2,2026-01-05,10,PURCHASE,RKO
109,Pembuatan PR & AF Requisition,MOR-W-20,3,2023-05-16,10,PURCHASE,RKO

28. SFE

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
10,Tear Down Inspection,IAU-W-03,3,2024-12-11,11,QC CHECK W/H,SFE
71,Cross Section Terminal & Pengecekan Circuit Si...,CDC-W-05,3,2025-08-08,5,QC LAB,SFE
73,Initial Process Study crimping,CDC-W-10,3,2025-09-26,11,QC LAB,SFE
81,"Pelaksanaan PPAP, ISIR & TR",PAP-P-01,2,2025-07-31,6,QC CHECK W/H,SFE
82,Pengisian Form PPAP Build Concern,PAP-W-08,3,2025-07-31,6,QC CHECK W/H,SFE
149,Voltage Test Dan Pengecheckan Scratch Core,PAM-W-19,3,2025-09-26,8,QC LAB,SFE
241,Pengendalian Alat Ukur,CMD-P-01,2,2021-12-22,8,QC MSA,SFE
242,Measurement System Analysis (MSA),CMD-P-02,2,2022-12-09,3,QC MSA,SFE
243,Pembuatan MSA Plan & Evaluation,CMD-W-01,3,2013-07-10,2,QC MSA,SFE
244,Analisa Hasil Kalibrasi,CMD-W-02,3,2025-11-07,6,QC MSA,SFE
246,Penaganan Kerusakan Atau Kehilangan Alat Ukur,CMD-W-04,3,2024-11-01,2,QC MSA,SFE

29. TWI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
6,Quality Meeting,MRE-W-01,3,2025-07-31,2,QA,TWI
11,Finish Good Sampling,IAU-W-06,3,2025-11-14,1,QA,TWI
13,Kakotora Audit,IAU-W-08,3,2025-08-28,1,QA,TWI
16,Layered Audit,IAU-W-11,3,2025-07-31,1,QA,TWI
18,8 Disciplines (8D),IMP-W-01,3,2025-08-15,3,QA,TWI
32,Pengajuan Training & License User Removal Tool,HRM-W-10,3,2025-08-22,3,QA,TWI
34,Penunjukkan Inspektor Baru,HRM-W-12,3,2018-12-11,5,QA,TWI
58,"Pembuatan, Pengontrolan & Review Berkala Dokum...",PQP-W-12,3,2024-10-04,14,QA,TWI
59,"Pembuatan, Pengontrolan & Review Berkala Dokum...",PQP-W-13,3,2024-10-04,12,QA,TWI
61,Initial Mass Production Intensive Quality Control,PQP-W-16,3,2025-08-28,1,QA,TWI
64,Identifikasi & Pengontrolan Proses Penting & P...,PQP-W-19,3,2019-10-22,2,QA,TWI
65,Initial Process Study Pengukuran Dimensi Clip ...,PQP-W-20,3,2023-12-02,0,QA,TWI
80,Mekanisme Penentuan Point Inspeksi,CDC-W-23,3,2019-10-25,1,QA,TWI
132,Lot Management Bonding,PAM-W-01,3,2026-01-15,6,QA,TWI
134,Set Up Verification,PAM-W-03,3,2025-09-26,14,QA,TWI
135,Pengisian Form Rework Pre Assy,PAM-W-04,3,2026-01-15,3,QA,TWI
150,Pengisian CS L/K Operator & Inspektor Manual C...,PAM-W-29,3,2025-08-14,4,QA,TWI
157,Statistical Process Control (SPC),PAM-W-44,3,2025-08-15,2,QA,TWI
160,Pengisian Checksheet Proses Anti Korosi (Ultra...,PAM-W-47,3,2023-12-02,0,QA,TWI
167,Pengisian CS Laporan Kerja Inspektor F/A,FAM-W-07,3,2025-07-31,12,QA,TWI
179,Control of Nonconforming Product,CNP-P-01,2,2025-07-31,9,QA,TWI
180,Pembuatan dan Pengisian Quality Alert,CNP-W-04,3,2025-11-19,10,QA,TWI
182,Product Sorting / Rework Instruction,CNP-W-06,3,2026-01-15,6,QA,TWI
183,Traceability Process,CNP-W-07,3,2025-11-19,2,QA,TWI
184,Perhitungan Quality Cost,CNP-W-09,3,2025-07-31,3,QA,TWI
185,Penanganan Product di Quarantine Area,CNP-W-11,3,2007-06-19,1,QA,TWI
187,Customer Complaint,CNP-W-13,3,2026-01-15,16,QA,TWI
188,Quality Notification / Business Memo,CNP-W-14,3,2025-08-22,1,QA,TWI
209,Approval Fuse Insertion Dan Fuse Verification ...,PFP-W-17,3,2025-07-31,1,QA,TWI
210,Pengisian Daily Check Inspector Dan GL Inspect,PFP-W-21,3,2025-09-26,9,QA,TWI
228,Review Equipment,ETM-W-20,3,2025-07-31,2,QA,TWI
229,Pengontrolan Inspection Jig,ETM-W-21,3,2025-10-14,5,QA,TWI
230,Pengontrolan Alat Potong,ETM-W-22,3,2025-11-14,1,QA,TWI

30. VRA

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
55,Pembuatan & Pengontrolan Operation Standard (OS),PQP-W-08,3,2025-08-07,5,DSG,VRA
76,Pembuatan Bonding Standart,CDC-W-13,3,2021-11-03,6,"DSG, QC LAB & MTC",VRA

31. VRA, ASW

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
20,Metode Distribusi Standard kerja,COD-W-02,3,2007-08-15,1,"DSG, QC STD","VRA, ASW"

32. WSU

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
75,Verifikasi Proses Crimping,CDC-W-12,3,2025-05-02,5,DSG,WSU
77,Temporary Crimping Standard,CDC-W-14,3,2025-11-12,1,DSG,WSU

33. WWI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
28,Training System,HRM-P-03,2,2025-11-07,10,TRAINING,WWI
29,Sistem Training Karyawan Baru dan Peserta Magang,HRM-W-03,3,2025-09-19,9,TRAINING,WWI
30,Pembuatan Dan Review Materi Training,HRM-W-05,3,2025-08-19,4,TRAINING,WWI
31,Prosedur Prakerin,HRM-W-08,3,2025-09-09,3,TRAINING,WWI
33,"Sistem Promosi Group Leader, Line Leader, Fore...",HRM-W-11,3,2025-09-24,7,TRAINING & HR,WWI
35,License Sistem,HRM-W-16,3,2025-09-09,5,TRAINING,WWI
36,Prosedur Renewal License,HRM-W-17,3,2025-09-09,2,TRAINING,WWI
37,Pelaporan Kehilangan Dan Atau Kerusakan Kartu ...,HRM-W-20,3,2025-08-19,1,TRAINING,WWI
38,Permohonan Pengesahan Perjanjian Magang Ke Dis...,HRM-W-21,3,2025-08-14,1,TRAINING,WWI
40,Prosedur Pengontrolan License,HRM-W-23,3,2025-09-09,5,TRAINING,WWI
41,Prosedur Pengontrolan License Eksternal,HRM-W-27,3,2025-09-09,1,TRAINING,WWI
46,Perubahan Atau Pembatalan Pelaksanaan Training,HRM-W-33,3,2025-08-19,1,TRAINING,WWI
47,Pendistribusian Dan Pengisian Form Request Tra...,HRM-W-35,3,2025-08-19,1,TRAINING,WWI

34. YFI

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
104,Mekanisme Approval,MOR-W-17,3,2025-08-21,20,FA,YFI

35. YHE

,Nama Dokumen,Nomor Dokumen,Level Dokumen,Tanggal Selesai Approval,Revisi,Owner,PIC
240,Review Dokumen (Checksheet) Mesin & Equipment ...,PPM-W-12,3,2025-12-22,0,PROD ENG,YHE

                PIC
0               ACA
1               AIN
2               ASE
3               ASW
4               ATH
5               CHA
6       DAF,YHE,TWI
7               DAS
8               DHS
9               DKR
10              EMU
11              ENS
12         ENS, TWI
13              FIR
14              HMA
15              HPU
16  HPU,TWI,DAS,YFI
17              HSW
18              ISR
19         ISR, AIN
20              LDA
21              LSE
22              MCB
23         MCB, DHS
24              MMR
25              NIA
26              RKO
27              SFE
28              TWI
29              VRA
30         VRA, ASW
31              WSU
32              WWI
33              YFI
34              YHE

In [5]:
df_pic.to_excel("../dokumen/daftar-pic.xlsx", index=False)

a
a
a
a
a
a
a
a
a
a